'use strict'
exports.NotificationService = require('./NotificationService')
exports.WebSocketService = require('./WebSocketService')
exports.DashboardService = require('./DashboardService')
exports.PluginService = require('./PluginService')
exports.FavoritesService = require('./FavoritesService')
exports.IRService = require('./IRService')
exports.DeviceService = require('./DeviceService')
exports.MdnsService = require('./MdnsService')
exports.ChatBotService = require('./ChatBotService')
